export const transformData = (data) => {
  const transformNode = (node) => ({
    id: node.emp_code,
    parentId: node.par_code,
    name: node.emp_name,
    positionName: node.position_name,
    department: node.dept_title,
    imageUrl: node.emp_img || "/images/profileImg/profileImg.png",
    _directSubordinates: node._directSubordinates,
    _totalSubordinates: node._totalSubordinates
  });

  const transformedData = data.map(transformNode);
  console.log("Transformed Data:", transformedData); // 변환된 데이터 확인

  return transformedData;
};


// 샘플 데이터
const employees = 
// [

  [
    {
      "position_code": "P1",
      "emp_code": 2020011,
      "par_code": null,
      "name": "박진영",
      "dept_code": "D1",
      "dept_title": "임원진",
      "positionName": "대표",
      "title_name": "대표",
      "phone": "010-1234-5678",
      "hire_date": "2020-01-01",
      "emp_status": "Y",
      "social_security_no": "1990-01-01",
      "emp_img": null,
      "children": [
        {
          "position_code": "P2",
          "emp_code": 2020021,
          "par_code": 2020011,
          "emp_name": "박은비",
          "dept_code": "D2",
          "dept_title": "전략기획부",
          "position_name": "이사",
          "title_name": "책임자",
          "phone": "010-2345-6789",
          "hire_date": "2020-02-15",
          "emp_status": "Y",
          "social_security_no": "1991-02-02",
          "emp_img": null,
          "children": [
            {
              "position_code": "P3",
              "emp_code": 2023061,
              "par_code": 2020021,
              "emp_name": "정지훈",
              "dept_code": "D10",
              "dept_title": "마케팅부",
              "position_name": "부장",
              "title_name": "부서장",
              "phone": "010-6789-0123",
              "hire_date": "2023-06-01",
              "emp_status": "Y",
              "social_security_no": "1995-06-06",
              "emp_img": null,
              "children": [
                {
                  "position_code": "P4",
                  "emp_code": 2022041,
                  "par_code": 2023061,
                  "emp_name": "강예지",
                  "dept_code": "D11",
                  "dept_title": "브랜드관리팀",
                  "position_name": "과장",
                  "title_name": "팀장",
                  "phone": "010-2345-6789",
                  "hire_date": "2022-04-05",
                  "emp_status": "Y",
                  "social_security_no": "1999-03-03",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2024031,
                  "par_code": 2023061,
                  "emp_name": "이수민",
                  "dept_code": "D12",
                  "dept_title": "디지털마케팅팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-1234-5678",
                  "hire_date": "2024-03-01",
                  "emp_status": "Y",
                  "social_security_no": "072232-1234567",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P4",
                  "emp_code": 2022091,
                  "par_code": 2023061,
                  "emp_name": "황민서",
                  "dept_code": "D12",
                  "dept_title": "디지털마케팅팀",
                  "position_name": "과장",
                  "title_name": "팀장",
                  "phone": "010-3456-7890",
                  "hire_date": "2022-09-15",
                  "emp_status": "Y",
                  "social_security_no": "2000-04-04",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2023032,
                  "par_code": 2023061,
                  "emp_name": "김서준",
                  "dept_code": "D11",
                  "dept_title": "브랜드관리팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-0123-4567",
                  "hire_date": "2023-03-10",
                  "emp_status": "Y",
                  "social_security_no": "072131-0123456",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P6",
                  "emp_code": 2023025,
                  "par_code": 2023061,
                  "emp_name": "이지훈",
                  "dept_code": "D12",
                  "dept_title": "디지털마케팅팀",
                  "position_name": "사원",
                  "title_name": "팀원",
                  "phone": "010-8901-2345",
                  "hire_date": "2023-02-25",
                  "emp_status": "Y",
                  "social_security_no": "2002-03-13",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2023021,
                  "par_code": 2023061,
                  "emp_name": "박준우",
                  "dept_code": "D11",
                  "dept_title": "브랜드관리팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-9012-3456",
                  "hire_date": "2023-02-15",
                  "emp_status": "Y",
                  "social_security_no": "072030-9012345",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2024041,
                  "par_code": 2023061,
                  "emp_name": "박시우",
                  "dept_code": "D12",
                  "dept_title": "디지털마케팅팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-2345-6789",
                  "hire_date": "2024-04-05",
                  "emp_status": "Y",
                  "social_security_no": "072333-2345678",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P6",
                  "emp_code": 2023014,
                  "par_code": 2023061,
                  "emp_name": "김현우",
                  "dept_code": "D11",
                  "dept_title": "브랜드관리팀",
                  "position_name": "사원",
                  "title_name": "팀원",
                  "phone": "010-7890-1234",
                  "hire_date": "2023-01-14",
                  "emp_status": "Y",
                  "social_security_no": "2001-12-20",
                  "emp_img": null,
                  "children": null
                }
              ]
            },
            {
              "position_code": "P3",
              "emp_code": 2022051,
              "par_code": 2020021,
              "emp_name": "강다영",
              "dept_code": "D7",
              "dept_title": "영업부",
              "position_name": "부장",
              "title_name": "부서장",
              "phone": "010-5678-9012",
              "hire_date": "2022-05-10",
              "emp_status": "Y",
              "social_security_no": "1994-05-05",
              "emp_img": null,
              "children": [
                {
                  "position_code": "P4",
                  "emp_code": 2024101,
                  "par_code": 2022051,
                  "emp_name": "박재원",
                  "dept_code": "D9",
                  "dept_title": "고객관리팀",
                  "position_name": "과장",
                  "title_name": "팀장",
                  "phone": "010-7890-1234",
                  "hire_date": "2024-10-30",
                  "emp_status": "Y",
                  "social_security_no": "2004-08-08",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2022111,
                  "par_code": 2022051,
                  "emp_name": "박서진",
                  "dept_code": "D8",
                  "dept_title": "영업기획팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-5678-9012",
                  "hire_date": "2022-11-01",
                  "emp_status": "Y",
                  "social_security_no": "071727-6789012",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P6",
                  "emp_code": 2022109,
                  "par_code": 2022051,
                  "emp_name": "김지현",
                  "dept_code": "D8",
                  "dept_title": "영업기획팀",
                  "position_name": "사원",
                  "title_name": "팀원",
                  "phone": "010-4567-8901",
                  "hire_date": "2022-10-01",
                  "emp_status": "N",
                  "social_security_no": "081515-4567890",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P6",
                  "emp_code": 2032092,
                  "par_code": 2022051,
                  "emp_name": "박성민",
                  "dept_code": "D9",
                  "dept_title": "고객관리팀",
                  "position_name": "사원",
                  "title_name": "팀원",
                  "phone": "010-3456-7890",
                  "hire_date": "2023-09-01",
                  "emp_status": "N",
                  "social_security_no": "071414-3456789",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P6",
                  "emp_code": 2022102,
                  "par_code": 2022051,
                  "emp_name": "김민성",
                  "dept_code": "D8",
                  "dept_title": "영업기획팀",
                  "position_name": "사원",
                  "title_name": "팀원",
                  "phone": "010-4567-8901",
                  "hire_date": "2022-10-22",
                  "emp_status": "Y",
                  "social_security_no": "1999-04-22",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P6",
                  "emp_code": 2022095,
                  "par_code": 2022051,
                  "emp_name": "박은지",
                  "dept_code": "D8",
                  "dept_title": "영업기획팀",
                  "position_name": "사원",
                  "title_name": "팀원",
                  "phone": "010-3456-7890",
                  "hire_date": "2022-09-15",
                  "emp_status": "Y",
                  "social_security_no": "1998-09-01",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2024012,
                  "par_code": 2022051,
                  "emp_name": "김유진",
                  "dept_code": "D8",
                  "dept_title": "영업기획팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-6789-0123",
                  "hire_date": "2024-01-01",
                  "emp_status": "Y",
                  "social_security_no": "2003-07-07",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2021056,
                  "par_code": 2022051,
                  "emp_name": "정수지",
                  "dept_code": "D9",
                  "dept_title": "고객관리팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-3456-7890",
                  "hire_date": "2021-05-16",
                  "emp_status": "Y",
                  "social_security_no": "1992-09-01",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2023035,
                  "par_code": 2022051,
                  "emp_name": "김서연",
                  "dept_code": "D9",
                  "dept_title": "고객관리팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-2345-6789",
                  "hire_date": "2023-03-25",
                  "emp_status": "N",
                  "social_security_no": "1996-08-08",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P6",
                  "emp_code": 2022125,
                  "par_code": 2022051,
                  "emp_name": "박준호",
                  "dept_code": "D9",
                  "dept_title": "고객관리팀",
                  "position_name": "사원",
                  "title_name": "팀원",
                  "phone": "010-6789-0123",
                  "hire_date": "2022-12-31",
                  "emp_status": "Y",
                  "social_security_no": "2000-11-03",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2022121,
                  "par_code": 2022051,
                  "emp_name": "김민지",
                  "dept_code": "D8",
                  "dept_title": "영업기획팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-6789-0123",
                  "hire_date": "2022-12-25",
                  "emp_status": "Y",
                  "social_security_no": "071828-7890123",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P6",
                  "emp_code": 2022119,
                  "par_code": 2022051,
                  "emp_name": "이승현",
                  "dept_code": "D9",
                  "dept_title": "고객관리팀",
                  "position_name": "사원",
                  "title_name": "팀원",
                  "phone": "010-5678-9012",
                  "hire_date": "2022-11-28",
                  "emp_status": "Y",
                  "social_security_no": "2000-04-28",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2023011,
                  "par_code": 2022051,
                  "emp_name": "이서아",
                  "dept_code": "D8",
                  "dept_title": "영업기획팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-7890-1234",
                  "hire_date": "2023-01-01",
                  "emp_status": "Y",
                  "social_security_no": "071929-8901234",
                  "emp_img": null,
                  "children": null
                },
                {
                  "position_code": "P5",
                  "emp_code": 2024035,
                  "par_code": 2022051,
                  "emp_name": "박시현",
                  "dept_code": "D9",
                  "dept_title": "고객관리팀",
                  "position_name": "대리",
                  "title_name": "팀원",
                  "phone": "010-3456-7890",
                  "hire_date": "2024-03-25",
                  "emp_status": "N",
                  "social_security_no": "1997-09-09",
                  "emp_img": null,
                  "children": null
                }
              ]
            }
          ]
        }
      ]
    }
  ]
  export default employees;

//   {
//     id: 1,
//     parentId: "",
//     name: "John",
//     positionName: "CEO",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "",
//     description:
//       "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
//     imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
//   },
//   {
//     id: 2,
//     parentId: "1",
//     name: "Smith",
//     positionName: "COO",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/20.jpg",
//   },

//   {
//     id: 3,
//     parentId: "1",
//     name: "Kate",
//     positionName: "CTO",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
//   },
//   {
//     id: 4,
//     parentId: "6",
//     team: "HR team",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//   },
//   {
//     id: 5,
//     parentId: "3",
//     name: "Erica",
//     positionName: "Manager of something",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/women/8.jpg",
//   },
//   {
//     id: 6,
//     parentId: "3",
//     name: "Paul",
//     positionName: "Manager of something",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
//   },
//   {
//     id: 7,
//     parentId: "5",
//     team: "Developers",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//   },
//   {
//     id: 8,
//     parentId: "3",
//     name: "Tony",
//     positionName: "Manager of something",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 9,
//     parentId: "2",
//     name: "Sally",
//     positionName: "Manager of something",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
//   },
//   {
//     id: 10,
//     parentId: "4",
//     name: "Scott",
//     positionName: "HR assistant",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
//   },

//   {
//     id: 11,
//     parentId: "1",
//     name: "James",
//     positionName: "CGO",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
//   },
//   {
//     id: 12,
//     parentId: "4",
//     name: "Tony",
//     positionName: "HR assistant",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 13,
//     parentId: "4",
//     name: "Sally",
//     positionName: "HR assistant",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
//   },
//   {
//     id: 14,
//     parentId: "8",
//     name: "Scott",
//     positionName: "Teacher",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
//   },

//   {
//     id: 15,
//     parentId: "8",
//     name: "James",
//     positionName: "Teacher",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
//   },
//   {
//     id: 16,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 17,
//     parentId: "7",
//     name: "Sally",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
//   },
//   {
//     id: 18,
//     parentId: "8",
//     name: "Scott",
//     positionName: "Teacher",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
//   },
//   {
//     id: 19,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 20,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 21,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 22,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 23,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 24,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 25,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 26,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
//   {
//     id: 27,
//     parentId: "7",
//     name: "Tony",
//     positionName: "Developer",
//     phone: "99887766",
//     email: "employee@email.com",
//     team: "",
//     location: "LA Branch",
//     department: "Marketing",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
//     imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
//   },
// ];

